// ─── AUTO-GENERATED — do not edit manually ────────────────────────────────────
// Updated by: GitHub Actions (daily) or local push
// Last updated: 2026-04-21

const CAPABILITIES = [
  { id:'content-production', name:'Content Production', cat:'content', icon:'✍️', desc:'Produce blog posts, whitepapers, LinkedIn posts, video scripts, carousels, and newsletters. One brief can generate a full multi-format content package.', powered:['odcus-blog','odcus-whitepaper','odcus-social','odcus-video','odcus-newsletter','odcus-linkedin-carousel','odcus-content-repurposing'], status:'active', automated:false },
  { id:'website-management', name:'Website Management', cat:'website', icon:'🌐', desc:'Full control of odcus.com: publish pages, manage CMS content, update design system, deploy custom code components, and fix SEO issues — all via Framer MCP.', powered:['Framer MCP','framer-website-manager','framer-cms','framer-seo','framer-code'], status:'active', automated:false },
  { id:'knowledge-management', name:'Knowledge Management', cat:'knowledge', icon:'🧠', desc:'Drop any document (PDF, DOCX, PPTX) into OneDrive and it auto-converts and lands in a curated consulting wiki across 7 disciplines. Searchable in every Claude session.', powered:['KB Watcher (24/7)','markitdown','QMD semantic search','odcus-kb-compile','odcus-kb-healthcheck'], status:'active', automated:true },
  { id:'seo', name:'SEO & Findability', cat:'seo', icon:'🔍', desc:'Technical audits, content optimization, programmatic SEO, structured data, local SEO, and AI search (GEO). Backed by live Ahrefs data and GSC integration.', powered:['Ahrefs MCP','seo-audit','seo-technical','seo-content','seo-schema','ai-seo','seo-programmatic'], status:'active', automated:false },
  { id:'market-intelligence', name:'Market Intelligence', cat:'intelligence', icon:'📡', desc:'Competitive landscape analysis, trend identification, Reddit community monitoring, and industry pain point mapping across 25 sectors.', powered:['competitive-intelligence-mx','trend-researcher','deep-research-specialist','reddit-intelligence-mx'], status:'active', automated:false },
  { id:'finance-ops', name:'Finance & Operations', cat:'finance', icon:'💰', desc:'Cash flow management, invoice creation and tracking, cost optimization, and 13-week runway forecasting — all connected to Bexio ERP.', powered:['Bexio MCP','treasury-cash-manager','financial-analyst-fs','cost-optimizer-fs','compliance-officer-fs'], status:'active', automated:false },
  { id:'sales-enablement', name:'Sales Enablement', cat:'sales', icon:'💼', desc:'Client use cases, consulting presentations, cold outreach sequences, proposal drafts, and meeting prep — built around Swiss SME buyer personas.', powered:['odcus-usecase','odcus-slides','cold-email','sales-enablement','sales-meeting-prep','prospect-pipeline'], status:'active', automated:false },
  { id:'visual-design', name:'Visual & Design', cat:'design', icon:'🎨', desc:'Brand-compliant illustrations, consulting slide decks, hand-drawn data tables, LinkedIn carousel visuals, and ad creatives via Canva MCP.', powered:['odcus-art','odcus-hand-drawn-tables','Canva MCP','odcus-linkedin-carousel','odcus-slides','banner-design'], status:'active', automated:false },
  { id:'business-strategy', name:'Business Strategy', cat:'strategy', icon:'📊', desc:'GTM strategy, pricing model design, partnership evaluation, product positioning, and market entry analysis for ODCUS and client engagements.', powered:['business-strategist-fs','pricing-strategist-fs','partnership-strategist-gr','risk-assessor-fs','investment-analyst-fs'], status:'active', automated:false },
];

const CAP_CATEGORIES = {
  content:      { label:'Content',       color:'#B57BE8', bg:'#200a35' },
  website:      { label:'Website',       color:'#61D2CE', bg:'#1a1a38' },
  knowledge:    { label:'Knowledge',     color:'#61D2CE', bg:'#1a2a28' },
  seo:          { label:'SEO',           color:'#7430F7', bg:'#250835' },
  intelligence: { label:'Intelligence',  color:'#B57BE8', bg:'#201528' },
  finance:      { label:'Finance',       color:'#61D2CE', bg:'#1a2a28' },
  sales:        { label:'Sales',         color:'#61D2CE', bg:'#1a2730' },
  design:       { label:'Design',        color:'#B57BE8', bg:'#1e1530' },
  strategy:     { label:'Strategy',      color:'#61D2CE', bg:'#1a2730' },
};

const WORKFLOWS = [
  { id:'content-pipeline', name:'Content Production Pipeline', icon:'✍️', color:'#B57BE8', bg:'#200a35', desc:'One whitepaper brief generates a full multi-channel content package. Each format is derived from the previous.', trigger:'Manual — topic brief or client angle', steps:[{name:'Brief',desc:'Topic, angle, target audience, Swiss SME pain point'},{name:'Whitepaper',desc:'2,500+ words, research-backed, IT advisory depth'},{name:'3–5 Blogs',desc:'Derived from whitepaper sections, SEO-optimized'},{name:'LinkedIn Posts',desc:'1–2 per blog, scheduled via Publer'},{name:'Video Scripts',desc:'30–60s scripts per blog topic'},{name:'Newsletter',desc:'Monthly digest compiled from blog content'}] },
  { id:'kb-pipeline', name:'Knowledge Base Pipeline', icon:'🧠', color:'#61D2CE', bg:'#1a2a28', desc:'Documents dropped in OneDrive are automatically converted, curated, and indexed. No manual intervention needed.', trigger:'Automatic — file drop in OneDrive Knowledge Process/', steps:[{name:'Drop Zone',desc:'OneDrive Knowledge Process/ folder'},{name:'File Watcher',desc:'fswatch monitors 24/7 via LaunchD'},{name:'markitdown',desc:'PDF/DOCX/PPTX/XLSX → markdown'},{name:'Raw Intake',desc:'Lands in knowhow/raw/'},{name:'KB Compile',desc:'Claude curates into 7 disciplines'},{name:'QMD Index',desc:'Re-indexed for BM25 + semantic search'}] },
  { id:'blog-publish', name:'Blog Publishing Flow', icon:'🌐', color:'#61D2CE', bg:'#1a1a38', desc:'From idea to published and distributed. Framer CMS publish + Publer scheduling happen in the same session.', trigger:'Manual — /odcus-blog skill or direct request', steps:[{name:'Research',desc:'Fetch sitemap, check existing content, load keyword strategy'},{name:'Draft',desc:'Write per Blog Style Guide, SEO-optimized'},{name:'Framer CMS',desc:'Publish via Framer MCP: slug, meta, hero image, HTML body'},{name:'Publer',desc:'Schedule LinkedIn post + promo comment'},{name:'Archive',desc:'Move source to _archive/, update blog-index.md'}] },
  { id:'daily-automation', name:'Daily KB Automation', icon:'⚙️', color:'#8719E1', bg:'#200a35', desc:'Runs every day at 16:30 Zurich time. Skips automatically if no new files have been added.', trigger:'Automatic — macOS LaunchD cron at 16:30 Zurich', steps:[{name:'Trigger',desc:'kb-daily.sh fires at 16:30 Zurich'},{name:'Check',desc:'Any new files in knowhow/raw/?'},{name:'Compile',desc:'Run /odcus-kb-compile on new files'},{name:'Health Check',desc:'Audit wiki: gaps, stale data, orphans'},{name:'Log',desc:'Write to 02-operations/logs/cron-kb-DATE.log'}] },
  { id:'rpi', name:'RPI Standard Process', icon:'🔄', color:'#7430F7', bg:'#1e1530', desc:'Standard operating procedure for all non-trivial tasks. Ensures quality, avoids hallucination, and gets alignment before execution.', trigger:'Any non-trivial content, strategy, or implementation task', steps:[{name:'Research',desc:'Fetch sitemap, read existing content, load context files — flag gaps'},{name:'Plan',desc:'State assumptions, propose approach — get explicit approval'},{name:'Implement',desc:'Execute agreed plan — flag deviations immediately'}] },
];

const AGENTS = [
  { id:'senior-software-engineer', name:'Senior Software Engineer', cat:'engineering', desc:'Complex feature implementation with architectural thinking, cross-functional technical leadership, and production-ready code delivery.' },
  { id:'frontend-developer', name:'Frontend Developer', cat:'engineering', desc:'React components, responsive layouts, client-side state management. Optimizes frontend performance and ensures accessibility.' },
  { id:'backend-architect', name:'Backend Architect', cat:'engineering', desc:'RESTful APIs, microservice boundaries, database schemas. Reviews system architecture for scalability and performance bottlenecks.' },
  { id:'ai-engineer', name:'AI Engineer', cat:'engineering', desc:'LLM applications, RAG systems, prompt pipelines. Implements vector search, agent orchestration, and AI API integrations.' },
  { id:'data-scientist', name:'Data Scientist', cat:'engineering', desc:'SQL queries, BigQuery operations, and data insights.' },
  { id:'data-engineer', name:'Data Engineer', cat:'engineering', desc:'ETL pipelines, data warehouses, and streaming architectures.' },
  { id:'python-pro', name:'Python Pro', cat:'engineering', desc:'Idiomatic Python with decorators, generators, async/await.' },
  { id:'code-reviewer', name:'Code Reviewer', cat:'engineering', desc:'Expert code review for quality, security, and maintainability.' },
  { id:'code-refactoring-expert', name:'Code Refactoring Expert', cat:'engineering', desc:'Improve code quality, reduce technical debt.' },
  { id:'code-analyzer-debugger', name:'Code Analyzer & Debugger', cat:'engineering', desc:'Investigate bugs, analyze code issues, perform root cause analysis.' },
  { id:'ui-ux-designer', name:'UI/UX Designer', cat:'product', desc:'Interface designs, wireframes, design systems.' },
  { id:'ui-designer', name:'UI Designer', cat:'product', desc:'Component creation, visual aesthetics, design systems.' },
  { id:'ui-ux-analyst', name:'UI/UX Analyst', cat:'product', desc:'Expert UI/UX analysis, design feedback, strategic guidance.' },
  { id:'product-manager-orchestrator', name:'Product Manager Orchestrator', cat:'product', desc:'Coordinate multiple specialized agents for complete product features.' },
  { id:'product-requirements-generator', name:'PRD Generator', cat:'product', desc:'Creates comprehensive Product Requirements Documents.' },
  { id:'product-engineer-at', name:'Product Engineer (AT)', cat:'product', desc:'Analyze customer use cases and map to product capabilities.' },
  { id:'ui-visual-validator', name:'UI Visual Validator', cat:'product', desc:'Verify UI modifications via screenshot analysis.' },
  { id:'business-strategist-fs', name:'Business Strategist', cat:'business', desc:'Strategic planning, competitive positioning, market entry strategies.' },
  { id:'business-analyst', name:'Business Analyst', cat:'business', desc:'Analyze metrics, create reports, and track KPIs.' },
  { id:'business-model-analyzer-mx', name:'Business Model Analyzer', cat:'business', desc:'Research monetization strategies, analyze business models.' },
  { id:'market-research-analyst', name:'Market Research Analyst', cat:'business', desc:'Comprehensive market intelligence, competitive analysis, industry trends.' },
  { id:'competitive-intelligence-mx', name:'Competitive Intelligence', cat:'business', desc:'Comprehensive competitive analysis and market positioning insights.' },
  { id:'trend-researcher', name:'Trend Researcher', cat:'business', desc:'Market opportunities, trending topics, viral content, emerging user behaviors.' },
  { id:'growth-hacker-gr', name:'Growth Hacker', cat:'marketing', desc:'Data-driven growth strategies, experiment design, funnel optimization.' },
  { id:'content-marketer-writer', name:'Content Marketer / Writer', cat:'marketing', desc:'Compelling, informative content. Article outlines, blog posts, direct response copy.' },
  { id:'customer-acquisition-gr', name:'Customer Acquisition', cat:'marketing', desc:'CAC optimization, funnel analysis, and multi-channel acquisition strategies.' },
  { id:'retention-specialist-gr', name:'Retention Specialist', cat:'marketing', desc:'Churn reduction, loyalty programs, customer lifecycle optimization.' },
  { id:'seo-content-writer', name:'SEO Content Writer', cat:'seo', desc:'SEO-optimized content based on keywords and topic briefs.' },
  { id:'seo-keyword-strategist', name:'SEO Keyword Strategist', cat:'seo', desc:'Analyzes keyword usage, calculates density, suggests semantic variations.' },
  { id:'seo-meta-optimizer', name:'SEO Meta Optimizer', cat:'seo', desc:'Optimized meta titles, descriptions, and URL suggestions.' },
  { id:'seo-structure-architect', name:'SEO Structure Architect', cat:'seo', desc:'Analyzes and optimizes content structure, header hierarchy, schema markup.' },
  { id:'seo-authority-builder', name:'SEO Authority Builder', cat:'seo', desc:'E-E-A-T signals and credibility improvements.' },
  { id:'seo-content-planner', name:'SEO Content Planner', cat:'seo', desc:'Comprehensive content outlines, topic clusters, content calendars.' },
  { id:'seo-content-auditor', name:'SEO Content Auditor', cat:'seo', desc:'Analyzes content for quality, E-E-A-T signals, and SEO best practices.' },
  { id:'seo-content-refresher', name:'SEO Content Refresher', cat:'seo', desc:'Identifies outdated elements in content.' },
  { id:'seo-snippet-hunter', name:'SEO Snippet Hunter', cat:'seo', desc:'Formats content for featured snippets and SERP features.' },
  { id:'seo-cannibalization-detector', name:'SEO Cannibalization Detector', cat:'seo', desc:'Analyzes multiple pages for keyword overlap.' },
  { id:'seo-performance', name:'SEO Performance', cat:'seo', desc:'Measures Core Web Vitals and page load performance.' },
  { id:'seo-visual', name:'SEO Visual', cat:'seo', desc:'Captures screenshots, tests mobile rendering.' },
  { id:'sales-engineer-gr', name:'Sales Engineer', cat:'sales', desc:'Technical sales support, solution architecture, demo preparation.' },
  { id:'sales-automator', name:'Sales Automator', cat:'sales', desc:'Cold emails, follow-ups, proposal templates, pricing pages, sales scripts.' },
  { id:'account-executive-revenue', name:'Account Executive (Revenue)', cat:'sales', desc:'Strategic account management focused on revenue growth.' },
  { id:'customer-success-manager', name:'Customer Success Manager', cat:'sales', desc:'Adoption patterns, value realization, renewal planning.' },
  { id:'customer-support', name:'Customer Support', cat:'sales', desc:'Support tickets, FAQ responses, help docs, troubleshooting guides.' },
  { id:'customer-support-at', name:'Customer Support (AT)', cat:'sales', desc:'Support issue analysis, resolution patterns, escalation risks.' },
  { id:'support-responder', name:'Support Responder', cat:'sales', desc:'Customer support handling, documentation, automated responses.' },
  { id:'managed-services-engineer', name:'Managed Services Engineer', cat:'sales', desc:'Product-customer alignment, release updates, optimization opportunities.' },
  { id:'financial-analyst-fs', name:'Financial Analyst', cat:'finance', desc:'Comprehensive financial analysis, ROI modeling, budget planning.' },
  { id:'treasury-cash-manager', name:'Treasury / Cash Manager', cat:'finance', desc:'Operational cash management, runway planning, 13-week forecasts.' },
  { id:'revenue-analyst-gr', name:'Revenue Analyst', cat:'finance', desc:'Revenue forecasting, pipeline analysis, growth metrics tracking.' },
  { id:'cost-optimizer-fs', name:'Cost Optimizer', cat:'finance', desc:'Comprehensive cost analysis, budget optimization, vendor management.' },
  { id:'pricing-strategist-fs', name:'Pricing Strategist', cat:'finance', desc:'Dynamic pricing analysis, revenue optimization, competitive pricing.' },
  { id:'investment-analyst-fs', name:'Investment Analyst', cat:'finance', desc:'M&A analysis, funding strategies, valuation modeling.' },
  { id:'risk-assessor-fs', name:'Risk Assessor', cat:'finance', desc:'Comprehensive risk modeling, scenario planning, business continuity analysis.' },
  { id:'risk-manager', name:'Risk Manager', cat:'finance', desc:'Portfolio risk, R-multiples, position limits. Creates hedging strategies.' },
  { id:'compliance-officer-fs', name:'Compliance Officer', cat:'finance', desc:'Regulatory compliance analysis, policy development, audit preparation.' },
  { id:'cloud-architect', name:'Cloud Architect', cat:'infrastructure', desc:'AWS/Azure/GCP infrastructure, Terraform IaC, auto-scaling, multi-region deployments.' },
  { id:'hybrid-cloud-architect', name:'Hybrid Cloud Architect', cat:'infrastructure', desc:'Hybrid cloud across AWS/Azure/GCP and OpenStack on-premises.' },
  { id:'network-engineer', name:'Network Engineer', cat:'infrastructure', desc:'Network connectivity, load balancers, DNS, SSL/TLS, CDN setup.' },
  { id:'incident-responder', name:'Incident Responder', cat:'infrastructure', desc:'Production incidents with urgency. Coordinates debugging, implements fixes.' },
  { id:'performance-engineer', name:'Performance Engineer', cat:'infrastructure', desc:'Profile applications, optimize bottlenecks, implement caching strategies.' },
  { id:'performance-optimizer', name:'Performance Optimizer', cat:'infrastructure', desc:'Analyze and improve system performance, eliminate bottlenecks.' },
  { id:'systems-architect', name:'Systems Architect', cat:'infrastructure', desc:'Scalable system architectures, architectural decisions, trade-off evaluation.' },
  { id:'security-auditor', name:'Security Auditor', cat:'security', desc:'Vulnerability reviews, OWASP compliance, JWT, OAuth2, CORS, CSP, encryption.' },
  { id:'security-threat-analyst', name:'Security Threat Analyst', cat:'security', desc:'Security assessments, threat modeling, vulnerability analysis.' },
  { id:'test-automator', name:'Test Automator', cat:'security', desc:'Unit, integration, and e2e test suites. CI pipelines, mocking strategies.' },
  { id:'docs-architect', name:'Docs Architect', cat:'docs', desc:'Comprehensive technical documentation from codebases.' },
  { id:'reference-builder', name:'Reference Builder', cat:'docs', desc:'Exhaustive technical references and API documentation.' },
  { id:'tutorial-engineer', name:'Tutorial Engineer', cat:'docs', desc:'Step-by-step tutorials and educational content.' },
  { id:'technical-mentor-guide', name:'Technical Mentor', cat:'docs', desc:'Explains technical concepts, creates educational content.' },
  { id:'automation-architect-aa', name:'Automation Architect', cat:'automation', desc:'Enterprise automation strategy, intelligent automation architecture.' },
  { id:'workflow-analyst-aa', name:'Workflow Analyst', cat:'automation', desc:'Process mapping, automation opportunity analysis, workflow optimization.' },
  { id:'integration-specialist-aa', name:'Integration Specialist', cat:'automation', desc:'API design, system integration, data flow optimization.' },
  { id:'ai-workflow-designer-aa', name:'AI Workflow Designer', cat:'automation', desc:'AI-powered workflow design, intelligent automation, human-AI collaboration.' },
  { id:'operations-optimizer-gr', name:'Operations Optimizer', cat:'operations', desc:'Process analysis, workflow automation, efficiency improvement.' },
  { id:'partnership-strategist-gr', name:'Partnership Strategist', cat:'operations', desc:'Partnership evaluation, channel strategy, integration planning.' },
  { id:'project-shipper', name:'Project Shipper', cat:'operations', desc:'Launch milestones, release processes, go-to-market strategies.' },
  { id:'sprint-prioritizer', name:'Sprint Prioritizer', cat:'operations', desc:'6-day development cycle planning, feature prioritization.' },
  { id:'deep-research-specialist', name:'Deep Research Specialist', cat:'research', desc:'Comprehensive, systematic research on complex topics.' },
  { id:'search-specialist', name:'Search Specialist', cat:'research', desc:'Expert web researcher using advanced search techniques.' },
  { id:'reddit-intelligence-mx', name:'Reddit Intelligence', cat:'research', desc:'Reddit communities for market intelligence and user sentiment.' },
  { id:'experience-analyzer-mx', name:'Experience Analyzer', cat:'research', desc:'Customer experience data to identify friction points.' },
  { id:'feedback-synthesizer', name:'Feedback Synthesizer', cat:'research', desc:'User feedback from multiple sources, pattern identification.' },
  { id:'prompt-engineer', name:'Prompt Engineer', cat:'specialized', desc:'Optimizes prompts for LLMs and AI systems.' },
  { id:'legal-advisor', name:'Legal Advisor', cat:'specialized', desc:'Privacy policies, terms of service, GDPR-compliant texts.' },
  { id:'context-manager', name:'Context Manager', cat:'specialized', desc:'Context across multiple agents and long-running tasks.' },
  { id:'tool-evaluator', name:'Tool Evaluator', cat:'specialized', desc:'New development tools, frameworks, or services evaluation.' },
  { id:'framer-website-manager', name:'Framer Website Manager', cat:'framer', desc:'ODCUS website management. Routes to specialized sub-agents.' },
  { id:'framer-cms', name:'Framer CMS', cat:'framer', desc:'Blog post creation/updates, CMS collection management.' },
  { id:'framer-page-builder', name:'Framer Page Builder', cat:'framer', desc:'Page creation, section insertion, layout changes.' },
  { id:'framer-code', name:'Framer Code', cat:'framer', desc:'Custom code components with React/TypeScript and Framer property controls.' },
  { id:'framer-design-system', name:'Framer Design System', cat:'framer', desc:'Color styles, text styles, and typography.' },
  { id:'framer-seo', name:'Framer SEO', cat:'framer', desc:'SEO issues: heading hierarchy, text style tags, alt text.' },
  { id:'content-strategy-agent', name:'Content Strategy Agent', cat:'content', desc:'Develops content strategies, editorial calendars, and topic prioritization.' },
  { id:'content-research-agent', name:'Content Research Agent', cat:'content', desc:'Deep content research, source validation, competitive content analysis.' },
  { id:'content-writer-agent', name:'Content Writer Agent', cat:'content', desc:'Long-form content writing with SEO optimization and brand voice.' },
  { id:'content-quality-agent', name:'Content Quality Agent', cat:'content', desc:'Content quality review, E-E-A-T analysis, readability scoring.' },
];

const AGENT_CATEGORIES = {
  engineering:    { label:'Engineering',         color:'#B57BE8', bg:'#1e1530' },
  product:        { label:'Product & Design',    color:'#8719E1', bg:'#200a35' },
  business:       { label:'Business & Strategy', color:'#61D2CE', bg:'#1a2730' },
  marketing:      { label:'Growth & Marketing',  color:'#B57BE8', bg:'#280a40' },
  seo:            { label:'SEO',                 color:'#7430F7', bg:'#250835' },
  sales:          { label:'Sales & CX',          color:'#61D2CE', bg:'#1a2730' },
  finance:        { label:'Finance',             color:'#61D2CE', bg:'#1a2a28' },
  infrastructure: { label:'Infrastructure',      color:'#8719E1', bg:'#1e1530' },
  security:       { label:'Security & QA',       color:'#ef4444', bg:'#2a1020' },
  docs:           { label:'Docs & Learning',     color:'#B57BE8', bg:'#1a1a38' },
  automation:     { label:'Automation',          color:'#8719E1', bg:'#200a35' },
  operations:     { label:'Operations',          color:'#61D2CE', bg:'#1a2730' },
  research:       { label:'Research',            color:'#B57BE8', bg:'#201528' },
  specialized:    { label:'Specialized',         color:'#B57BE8', bg:'#1e1530' },
  framer:         { label:'Framer / Website',    color:'#61D2CE', bg:'#1a1a38' },
  content:        { label:'Content Pipeline',    color:'#B57BE8', bg:'#200a35' },
};

const SKILLS = [
  { id:'seo', name:'SEO', cat:'seo', desc:'Full site audits, technical SEO, Core Web Vitals, schema, content quality, GEO.' },
  { id:'seo-audit', name:'SEO Audit', cat:'seo', desc:'Comprehensive SEO audit workflow covering technical, content, backlinks, and performance.' },
  { id:'seo-plan', name:'SEO Plan', cat:'seo', desc:'Strategic SEO planning and roadmap creation.' },
  { id:'seo-competitor-pages', name:'SEO Competitor Pages', cat:'seo', desc:'Competitive content gap analysis and competitor page research.' },
  { id:'seo-content', name:'SEO Content', cat:'seo', desc:'Content quality review with E-E-A-T signals, readability, AI citation readiness.' },
  { id:'seo-dataforseo', name:'SEO DataForSEO', cat:'seo', desc:'Live SERP data, keyword metrics, backlink profiles via DataForSEO MCP.' },
  { id:'seo-geo', name:'SEO GEO', cat:'seo', desc:'GEO and AI search: AI crawler accessibility, llms.txt compliance, brand mention signals.' },
  { id:'seo-hreflang', name:'SEO Hreflang', cat:'seo', desc:'International SEO hreflang implementation and validation.' },
  { id:'seo-image-gen', name:'SEO Image Gen', cat:'seo', desc:'Audits OG/social preview images, creates image generation plan.' },
  { id:'seo-images', name:'SEO Images', cat:'seo', desc:'Image optimization for SEO: alt text, file names, compression, formats.' },
  { id:'seo-local', name:'SEO Local', cat:'seo', desc:'Local SEO: GBP signals, NAP consistency, citations, reviews, local schema.' },
  { id:'seo-page', name:'SEO Page', cat:'seo', desc:'Single-page SEO deep analysis and optimization.' },
  { id:'seo-programmatic', name:'SEO Programmatic', cat:'seo', desc:'Programmatic SEO at scale: template design, variable mapping, bulk generation.' },
  { id:'seo-schema', name:'SEO Schema', cat:'seo', desc:'Schema markup expert: detects, validates, generates Schema.org structured data.' },
  { id:'seo-sitemap', name:'SEO Sitemap', cat:'seo', desc:'Sitemap architect: validates XML sitemaps, generates new ones.' },
  { id:'seo-technical', name:'SEO Technical', cat:'seo', desc:'Technical SEO: crawlability, indexability, URL structure, Core Web Vitals.' },
  { id:'ai-seo', name:'AI SEO', cat:'seo', desc:'AI-specific SEO strategies for generative search engines and AI Overviews.' },
  { id:'programmatic-seo', name:'Programmatic SEO', cat:'seo', desc:'Programmatic SEO strategy and execution at scale.' },
  { id:'content-strategy', name:'Content Strategy', cat:'marketing', desc:'Content strategy development, editorial calendar planning.' },
  { id:'copywriting', name:'Copywriting', cat:'marketing', desc:'Conversion-focused copywriting for web, ads, emails, and sales materials.' },
  { id:'copy-editing', name:'Copy Editing', cat:'marketing', desc:'Editorial review, grammar, style consistency, and brand voice alignment.' },
  { id:'social-content', name:'Social Content', cat:'marketing', desc:'Social media content creation for LinkedIn, Twitter, Instagram.' },
  { id:'blog-sync', name:'Blog Sync', cat:'marketing', desc:'Synchronize blog content across platforms and CMS systems.' },
  { id:'email-sequence', name:'Email Sequence', cat:'marketing', desc:'Drip email sequences, nurture campaigns, and automated email flows.' },
  { id:'cold-email', name:'Cold Email', cat:'marketing', desc:'Cold outreach email writing, subject lines, and follow-up sequences.' },
  { id:'sales-enablement', name:'Sales Enablement', cat:'marketing', desc:'Sales collateral, battle cards, case studies, and enablement materials.' },
  { id:'sales-meeting-prep', name:'Sales Meeting Prep', cat:'marketing', desc:'Pre-meeting research, talk tracks, objection handling preparation.' },
  { id:'marketing-ideas', name:'Marketing Ideas', cat:'marketing', desc:'Creative marketing campaign ideas, channel strategies, and growth tactics.' },
  { id:'marketing-psychology', name:'Marketing Psychology', cat:'marketing', desc:'Behavioral psychology principles applied to marketing copy and UX.' },
  { id:'paid-ads', name:'Paid Ads', cat:'marketing', desc:'Paid advertising strategy, ad copy, targeting, and campaign optimization.' },
  { id:'ad-creative', name:'Ad Creative', cat:'marketing', desc:'Ad creative concepts, visual briefs, and copy variations.' },
  { id:'analytics-tracking', name:'Analytics Tracking', cat:'marketing', desc:'Analytics implementation, event tracking, conversion measurement.' },
  { id:'humanizer', name:'Humanizer', cat:'marketing', desc:'Transforms AI-generated text into natural, human-sounding content.' },
  { id:'ab-test-setup', name:'A/B Test Setup', cat:'cro', desc:'A/B test design, hypothesis creation, statistical significance planning.' },
  { id:'form-cro', name:'Form CRO', cat:'cro', desc:'Form optimization for higher conversion.' },
  { id:'page-cro', name:'Page CRO', cat:'cro', desc:'Landing page conversion optimization: layout, copy, CTAs, trust signals.' },
  { id:'popup-cro', name:'Popup CRO', cat:'cro', desc:'Popup and modal optimization for email capture and conversions.' },
  { id:'onboarding-cro', name:'Onboarding CRO', cat:'cro', desc:'User onboarding flow optimization for activation and retention.' },
  { id:'paywall-upgrade-cro', name:'Paywall / Upgrade CRO', cat:'cro', desc:'Paywall and upgrade page optimization for paid conversion.' },
  { id:'signup-flow-cro', name:'Signup Flow CRO', cat:'cro', desc:'Signup funnel optimization from first touch to activation.' },
  { id:'referral-program', name:'Referral Program', cat:'cro', desc:'Referral program design, mechanics, copy, and growth loops.' },
  { id:'churn-prevention', name:'Churn Prevention', cat:'cro', desc:'Churn analysis, intervention design, and retention strategy.' },
  { id:'design', name:'Design', cat:'design', desc:'General design skill covering layout, visual hierarchy, and component design.' },
  { id:'design-system', name:'Design System', cat:'design', desc:'Design system creation, component libraries, token management.' },
  { id:'ui-styling', name:'UI Styling', cat:'design', desc:'CSS and styling implementation, theming, responsive design.' },
  { id:'ui-ux-pro-max', name:'UI/UX Pro Max', cat:'design', desc:'Advanced UI/UX design with deep user research.' },
  { id:'banner-design', name:'Banner Design', cat:'design', desc:'Marketing banner design for web, social, and display advertising.' },
  { id:'site-architecture', name:'Site Architecture', cat:'design', desc:'Information architecture, site structure, navigation design.' },
  { id:'slides', name:'Slides', cat:'design', desc:'Presentation design and slide creation.' },
  { id:'schema-markup', name:'Schema Markup', cat:'design', desc:'Structured data implementation for search engines and AI systems.' },
  { id:'brand', name:'Brand', cat:'business', desc:'Brand strategy, identity, voice, and guidelines development.' },
  { id:'competitor-alternatives', name:'Competitor Alternatives', cat:'business', desc:'Competitor alternative pages and comparison content strategy.' },
  { id:'pricing-strategy', name:'Pricing Strategy', cat:'business', desc:'Pricing model design, tiering, packaging, and revenue optimization.' },
  { id:'free-tool-strategy', name:'Free Tool Strategy', cat:'business', desc:'Free tool/resource strategy for lead generation and SEO.' },
  { id:'product-marketing-context', name:'Product Marketing Context', cat:'business', desc:'Product positioning, messaging, and go-to-market context.' },
  { id:'website-orchestrator', name:'Website Orchestrator', cat:'business', desc:'Orchestrates end-to-end website projects.' },
  { id:'website-reviewer', name:'Website Reviewer', cat:'business', desc:'Comprehensive website review covering UX, content, SEO, and conversion.' },
  { id:'prospect-pipeline', name:'Prospect Pipeline', cat:'business', desc:'Sales pipeline management, prospect research, and outreach sequencing.' },
  { id:'revops', name:'RevOps', cat:'business', desc:'Revenue operations: CRM, pipeline hygiene, forecasting, and GTM alignment.' },
  { id:'launch-strategy', name:'Launch Strategy', cat:'business', desc:'Product and campaign launch strategy, sequencing, and execution.' },
  { id:'odcus-blog', name:'ODCUS Blog', cat:'odcus', desc:'Full blog post creation workflow for ODCUS: research, draft, SEO optimize, publish to Framer CMS.' },
  { id:'odcus-whitepaper', name:'ODCUS Whitepaper', cat:'odcus', desc:'Whitepaper creation for ODCUS IT advisory topics targeting Swiss SME decision-makers.' },
  { id:'odcus-social', name:'ODCUS Social', cat:'odcus', desc:'LinkedIn content creation, scheduling via Publer, and social media strategy.' },
  { id:'odcus-video', name:'ODCUS Video', cat:'odcus', desc:'Video script writing, talking points, and video content strategy.' },
  { id:'odcus-slides', name:'ODCUS Slides', cat:'odcus', desc:'Presentation and slide creation in ODCUS brand style.' },
  { id:'odcus-art', name:'ODCUS Art', cat:'odcus', desc:'Brand illustration and visual art creation following ODCUS Brand Style Guide.' },
  { id:'odcus-usecase', name:'ODCUS Use Case', cat:'odcus', desc:'Client use case documentation and storytelling.' },
  { id:'odcus-knowhow', name:'ODCUS Knowhow', cat:'odcus', desc:'Internal knowledge base articles on IT advisory topics.' },
  { id:'odcus-linkedin-carousel', name:'ODCUS LinkedIn Carousel', cat:'odcus', desc:'LinkedIn carousel post creation: slide structure, copy, and visual direction.' },
  { id:'odcus-content-pipeline', name:'ODCUS Content Pipeline', cat:'odcus', desc:'End-to-end content production pipeline from idea to publish.' },
  { id:'odcus-content-repurposing', name:'ODCUS Content Repurposing', cat:'odcus', desc:'Repurpose existing content across formats.' },
  { id:'odcus-hand-drawn-tables', name:'ODCUS Hand-Drawn Tables', cat:'odcus', desc:'Create hand-drawn style data tables for visual content.' },
  { id:'odcus-newsletter', name:'ODCUS Newsletter', cat:'odcus', desc:'ODCUS email newsletter creation and distribution strategy.' },
  { id:'odcus-kb-compile', name:'KB Compile', cat:'odcus', desc:'Compile and organize the ODCUS knowledge base from raw content.' },
  { id:'odcus-kb-healthcheck', name:'KB Healthcheck', cat:'odcus', desc:'Audit and validate the ODCUS knowledge base.' },
];

const SKILL_CATEGORIES = {
  seo:      { label:'SEO',                color:'#7430F7', bg:'#250835' },
  marketing:{ label:'Marketing & Content', color:'#B57BE8', bg:'#280a40' },
  cro:      { label:'CRO & Growth',       color:'#8719E1', bg:'#200a35' },
  design:   { label:'Design & UI',        color:'#B57BE8', bg:'#1e1530' },
  business: { label:'Business Strategy',  color:'#61D2CE', bg:'#1a2730' },
  odcus:    { label:'ODCUS Specific',     color:'#61D2CE', bg:'#200a35' },
};

const MEMORY_ITEMS = [
  { type:'project', title:'ODCUS Business Model', desc:'Managed AI Operations service for Swiss businesses: 3-phase model, pricing, GTM strategy.' },
  { type:'project', title:'Paperclip Company', desc:'Company/agent IDs, issue prefix ODA, agent roster.' },
  { type:'reference', title:'Industry Pain Points', desc:'25 industries with specific operational bottlenecks and AI solutions to pitch.' },
  { type:'feedback', title:'Daily Log', desc:'End each session by updating 02-operations/logs/YYYY-MM-DD.md with what was done.' },
  { type:'feedback', title:'Website Differentiation', desc:'Pipeline websites must be structurally unique per business.' },
  { type:'feedback', title:'Skill Creation Tips', desc:'Always add Gotchas section, use progressive disclosure, description = trigger not summary.' },
  { type:'feedback', title:'Blog Display Image', desc:'Use random B&W brand photo from OneDrive ODCUS Material/06. Brand Photos/BlackWhite.' },
  { type:'feedback', title:'No Exaggeration', desc:'Use "in our experience" not "every company," no AI-slop words, plain language.' },
  { type:'feedback', title:'LinkedIn Publer Comment', desc:'Always add standard ODCUS promo comment to every LinkedIn post scheduled via Publer.' },
  { type:'feedback', title:'Blog Images in Content', desc:'When publishing blogs, always embed content infographics in the HTML body.' },
  { type:'feedback', title:'Presentations: Sell What Not How', desc:'Teach what\'s possible and why, never step-by-step how.' },
  { type:'feedback', title:'Content: Industry Pain Points First', desc:'Content must start from the specific industry pain point, never from AI/technology.' },
  { type:'feedback', title:'Content Structure', desc:'All content: one idea, story/example, reasons (not steps), soft CTA.' },
  { type:'feedback', title:'Cut Non-Behavior Content', desc:'Cut anything that doesn\'t change reader behavior.' },
];

const MCP_SERVERS = [
  { name:'Framer', id:'framer', color:'#61D2CE', desc:'Website CMS, page building, code components, design system, SEO for odcus.com', tools:['getProjectXml','getCMSItems','upsertCMSItem','createPage','updateCodeFile','manageColorStyle'] },
  { name:'Bexio', id:'bexio', color:'#61D2CE', desc:'Swiss ERP: invoices, contacts, orders, quotes, projects, timesheets, payments', tools:['invoices_list','contacts_list','projects_list','orders_list','quotes_list','timesheets_list'] },
  { name:'Ahrefs', id:'ahrefs', color:'#7430F7', desc:'SEO data: keyword explorer, site explorer, rank tracker, site audit, web analytics, brand radar, GSC', tools:['keywords-explorer-overview','site-explorer-metrics','rank-tracker-overview','site-audit-issues','gsc-keywords'] },
  { name:'Supabase', id:'supabase', color:'#B57BE8', desc:'Database, edge functions, migrations, branching, TypeScript types generation', tools:['execute_sql','apply_migration','deploy_edge_function','list_tables','create_branch'] },
  { name:'Canva', id:'canva', color:'#8719E1', desc:'Design creation, brand kits, asset management, design editing, exports', tools:['generate-design','get-assets','list-brand-kits','export-design','start-editing-transaction'] },
  { name:'Playwright', id:'playwright', color:'#ef4444', desc:'Browser automation: screenshots, navigation, form filling, interaction, testing', tools:['browser_navigate','browser_take_screenshot','browser_fill_form','browser_click','browser_snapshot'] },
  { name:'HubSpot', id:'hubspot', color:'#B57BE8', desc:'CRM: contacts, deals, campaigns, analytics, pipeline management', tools:['get_crm_objects','search_crm_objects','get_campaign_analytics','get_organization_details'] },
  { name:'QMD', id:'qmd', color:'#61D2CE', desc:'Local search over ODCUS knowledge base: 4 docs, BM25 + semantic + Hyde search', tools:['query','get','multi_get','status'] },
];
